logging:
  level: INFO
  loggers:
    org.sweatshop: DEBUG
template: Hello, %s!
defaultName: Stranger
headerFile: "src/main/resources/header.html"
footerFile: "src/main/resources/footer.html"
filesDir: "src/main/resources/files"